### ISSUE TITLE
当姓名为特殊字符会发生崩溃

### ISSUE THREAD

**Issue by lumianie** [Baymax0/BMChineseSort#1]
当姓名为“#”或者“？”等特殊字符时会崩溃在        NSString *pinyin = [str substringToIndex:1];这一句，原因是ReturnSortObjectArrar方法返回特殊字符时chineseString.pinYin = @""导致crash，改成chineseString.pinYin = @"#";解决问题

**Comment by Baymax0** [comment]
恩  已修复O(∩_∩)O~
