### ISSUE TITLE
同一拼音首字母时顺序错乱

### ISSUE THREAD

**Issue by PreAnti** [Baymax0/BMChineseSort#11]
比如：
1.李某、刘某（这是正常顺序）。现在排出来的结果是刘某、李某。
2.韩某、韩某某、贺某（这是正常顺序）。现在排出来的结果是韩某、贺某、韩某某。

**Comment by Baymax0** [comment]
我看了下，我猜你应该用的oc吧，下面的更新我也只改动了oc的版本，swift还没动
因为用了enumerateObjectsWithOptions:NSEnumerationConcurrent...方法多线程异步转换拼音的原因，导致第一轮转换后顺序打乱了，所以最终的排序结果是不稳定的。
我给加了needStable属性，默认是false，需要稳定排序的话使用前设为true就好了
BMChineseSortSetting.share.needStable = true;
这操作我暂时是替换了多线程方法为单线程的方法，所以如果数据量大的话可能速度会有影响。

**Comment by Baymax0** [comment]
我只是初步测试了下，如果还有问题欢迎继续反馈

**Comment by PreAnti** [comment]
Objective-C和Swift都在用，不过当前项目用Objective-C开发的。
