### ISSUE TITLE
能不能支持一下CocoaPods, SPM????

### ISSUE THREAD

**Issue by CainLuo** [Baymax0/BMChineseSort#17]
能不能支持一下CocoaPods, SPM????

**Comment by Baymax0** [comment]
体量太小就没整  我看看SPM
你也可以自己支持完Pull 上来我合并进去

**Comment by Baymax0** [comment]
https://github.com/Baymax0/BMChineseSortSwift
给swift版本拿出来 支持SPM了，oc的和CocoaPods没空整了

**Comment by CainLuo** [comment]
CocoaPods没法给你弄啊, 不然这个库就到我的名下了 @Baymax0

**Comment by CainLuo** [comment]
不过podspec可以帮你写, 但是你要自己推到CocoaPods @Baymax0

**Comment by Baymax0** [comment]
哈哈 过两天我看看 最近比较忙

**Comment by Baymax0** [comment]
@CainLuo  你也有玩吉他呀 可以加个v  交流交流呀 哈哈哈  我指弹 弹唱 都会点

**Comment by CainLuo** [comment]
@Baymax0 已经帮你写好, 你合并一下分支就好了, 现在好久没玩了, 工作太忙了
